import { useState } from 'react';
import jsPDF from 'jspdf';
import { api } from '../api/client';
import dayjs from 'dayjs';

interface ExportPDFButtonProps {
    selectedMonth: string;
}

export default function ExportPDFButton({ selectedMonth }: ExportPDFButtonProps) {
    const [loading, setLoading] = useState(false);

    const formatRupiah = (amount: number): string => {
        return new Intl.NumberFormat('id-ID', {
            style: 'currency',
            currency: 'IDR',
            minimumFractionDigits: 0,
            maximumFractionDigits: 0
        }).format(amount);
    };

    const formatDate = (dateISO: string): string => {
        return dayjs(dateISO).format('DD MMM');
    };

    const formatMonth = (yearMonth: string): string => {
        return dayjs(yearMonth + '-01').format('MMMM YYYY');
    };

    const generatePDF = async () => {
        try {
            setLoading(true);

            // Fetch all data for the month
            const [transactions, income, categories, expenseSources, incomeSources, summary, breakdown] = await Promise.all([
                api.getTransactions(selectedMonth),
                api.getIncome(selectedMonth),
                api.getCategories(),
                api.getExpenseSources(),
                api.getIncomeSources(),
                api.getSummary(selectedMonth),
                api.getBreakdown(selectedMonth)
            ]);

            // Create maps for lookups
            const categoryMap = new Map(categories.map(c => [c.id, c.name]));
            const expenseSourceMap = new Map(expenseSources.map(s => [s.id, s.name]));
            const incomeSourceMap = new Map(incomeSources.map(s => [s.id, s.name]));

            // Create PDF (A4: 210 x 297 mm)
            const doc = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            const pageWidth = 210;
            const pageHeight = 297;
            const margin = 15;
            const contentWidth = pageWidth - (margin * 2);
            let y = margin;

            // Colors
            const primaryColor = [59, 130, 246] as [number, number, number]; // Blue
            const greenColor = [34, 197, 94] as [number, number, number]; // Green
            const grayColor = [107, 114, 128] as [number, number, number];
            const darkColor = [31, 41, 55] as [number, number, number];

            // Helper: Add page footer
            const addFooter = (pageNum: number, totalPages: number) => {
                doc.setFontSize(8);
                doc.setTextColor(...grayColor);
                doc.text(`Page ${pageNum} of ${totalPages}`, margin, pageHeight - 10);
                doc.text('Generated by RM Financial Tracker', pageWidth - margin, pageHeight - 10, { align: 'right' });
            };

            // Helper: Check if we need new page
            const checkNewPage = (neededHeight: number): boolean => {
                if (y + neededHeight > pageHeight - 25) {
                    doc.addPage();
                    y = margin;
                    return true;
                }
                return false;
            };

            // ============================================
            // HEADER
            // ============================================
            doc.setFillColor(...primaryColor);
            doc.rect(0, 0, pageWidth, 40, 'F');

            doc.setTextColor(255, 255, 255);
            doc.setFontSize(20);
            doc.setFont('helvetica', 'bold');
            doc.text('RM FINANCIAL TRACKER', margin, 18);

            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.text(`Statement for ${formatMonth(selectedMonth)}`, margin, 28);

            doc.setFontSize(9);
            doc.text(`Generated: ${dayjs().format('DD MMM YYYY, HH:mm')} WIB`, margin, 35);

            y = 50;

            // ============================================
            // SUMMARY SECTION
            // ============================================
            doc.setTextColor(...darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('FINANCIAL SUMMARY', margin, y);
            y += 8;

            // Summary boxes
            const boxWidth = (contentWidth - 9) / 4;
            const boxHeight = 22;

            const summaryItems = [
                { label: 'Total Income', value: formatRupiah(summary.totalIncome || 0), color: greenColor },
                { label: 'Total Expenses', value: formatRupiah(summary.totalCurrent || 0), color: [239, 68, 68] as [number, number, number] },
                { label: 'Net Savings', value: formatRupiah(summary.netSavings || 0), color: summary.netSavings >= 0 ? greenColor : [239, 68, 68] as [number, number, number] },
                { label: 'Savings Rate', value: `${(summary.savingsRate || 0).toFixed(1)}%`, color: primaryColor }
            ];

            summaryItems.forEach((item, i) => {
                const x = margin + (i * (boxWidth + 3));
                doc.setFillColor(248, 250, 252);
                doc.roundedRect(x, y, boxWidth, boxHeight, 2, 2, 'F');

                doc.setFontSize(8);
                doc.setTextColor(...grayColor);
                doc.setFont('helvetica', 'normal');
                doc.text(item.label, x + 3, y + 6);

                doc.setFontSize(11);
                doc.setTextColor(...item.color);
                doc.setFont('helvetica', 'bold');
                doc.text(item.value, x + 3, y + 15);
            });

            y += boxHeight + 12;

            // ============================================
            // EXPENSES TABLE
            // ============================================
            checkNewPage(50);
            doc.setTextColor(...darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text(`EXPENSES (${transactions.length} transactions)`, margin, y);
            y += 6;

            // Table header
            doc.setFillColor(...primaryColor);
            doc.rect(margin, y, contentWidth, 7, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'bold');
            doc.text('Date', margin + 2, y + 5);
            doc.text('Category', margin + 22, y + 5);
            doc.text('Source', margin + 55, y + 5);
            doc.text('Description', margin + 85, y + 5);
            doc.text('Amount', margin + contentWidth - 2, y + 5, { align: 'right' });
            y += 7;

            // Table rows
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...darkColor);

            const sortedTransactions = [...transactions].sort((a, b) => {
                if (!a.dateISO || !b.dateISO) return 0;
                return a.dateISO.localeCompare(b.dateISO);
            });

            sortedTransactions.forEach((txn, i) => {
                checkNewPage(6);

                // Alternate row color
                if (i % 2 === 0) {
                    doc.setFillColor(249, 250, 251);
                    doc.rect(margin, y, contentWidth, 6, 'F');
                }

                doc.setFontSize(8);
                doc.setTextColor(...darkColor);
                doc.text(formatDate(txn.dateISO), margin + 2, y + 4);
                doc.text((categoryMap.get(txn.categoryId) || 'Unknown').substring(0, 15), margin + 22, y + 4);
                doc.text((txn.sourceId ? expenseSourceMap.get(txn.sourceId) || '-' : '-').substring(0, 12), margin + 55, y + 4);
                doc.text(txn.description.substring(0, 30), margin + 85, y + 4);
                doc.text(formatRupiah(txn.amountRp), margin + contentWidth - 2, y + 4, { align: 'right' });
                y += 6;
            });

            // Expenses total
            doc.setFillColor(243, 244, 246);
            doc.rect(margin, y, contentWidth, 7, 'F');
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9);
            doc.text('Total Expenses', margin + 2, y + 5);
            doc.text(formatRupiah(summary.totalCurrent || 0), margin + contentWidth - 2, y + 5, { align: 'right' });
            y += 12;

            // ============================================
            // INCOME TABLE
            // ============================================
            checkNewPage(50);
            doc.setTextColor(...darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text(`INCOME (${income.length} entries)`, margin, y);
            y += 6;

            // Table header
            doc.setFillColor(...greenColor);
            doc.rect(margin, y, contentWidth, 7, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'bold');
            doc.text('Date', margin + 2, y + 5);
            doc.text('Source', margin + 25, y + 5);
            doc.text('Description', margin + 70, y + 5);
            doc.text('Amount', margin + contentWidth - 2, y + 5, { align: 'right' });
            y += 7;

            // Table rows
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...darkColor);

            const sortedIncome = [...income].sort((a, b) => {
                if (!a.dateISO || !b.dateISO) return 0;
                return a.dateISO.localeCompare(b.dateISO);
            });

            sortedIncome.forEach((inc, i) => {
                checkNewPage(6);

                if (i % 2 === 0) {
                    doc.setFillColor(249, 250, 251);
                    doc.rect(margin, y, contentWidth, 6, 'F');
                }

                doc.setFontSize(8);
                doc.setTextColor(...darkColor);
                doc.text(formatDate(inc.dateISO), margin + 2, y + 4);
                doc.text((incomeSourceMap.get(inc.sourceId) || 'Unknown').substring(0, 20), margin + 25, y + 4);
                doc.text(inc.description.substring(0, 45), margin + 70, y + 4);
                doc.setTextColor(...greenColor);
                doc.text(formatRupiah(inc.amountRp), margin + contentWidth - 2, y + 4, { align: 'right' });
                y += 6;
            });

            // Income total
            doc.setFillColor(236, 253, 245);
            doc.rect(margin, y, contentWidth, 7, 'F');
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(9);
            doc.setTextColor(...darkColor);
            doc.text('Total Income', margin + 2, y + 5);
            doc.setTextColor(...greenColor);
            doc.text(formatRupiah(summary.totalIncome || 0), margin + contentWidth - 2, y + 5, { align: 'right' });
            y += 12;

            // ============================================
            // CATEGORY BREAKDOWN
            // ============================================
            checkNewPage(60);
            doc.setTextColor(...darkColor);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('EXPENSE BREAKDOWN BY CATEGORY', margin, y);
            y += 8;

            const totalExpenses = summary.totalCurrent || 1;
            const sortedBreakdown = [...breakdown].sort((a, b) => b.total - a.total);

            sortedBreakdown.forEach((item, _i) => {
                checkNewPage(10);

                const categoryName = categoryMap.get(item.categoryId) || 'Unknown';
                const percentage = (item.total / totalExpenses) * 100;
                const barWidth = (percentage / 100) * (contentWidth - 60);

                doc.setFontSize(9);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(...darkColor);
                doc.text(categoryName, margin, y + 4);

                // Progress bar background
                doc.setFillColor(229, 231, 235);
                doc.rect(margin + 35, y, contentWidth - 95, 5, 'F');

                // Progress bar fill
                doc.setFillColor(...primaryColor);
                doc.rect(margin + 35, y, Math.max(barWidth, 2), 5, 'F');

                doc.text(`${percentage.toFixed(1)}%`, margin + contentWidth - 35, y + 4);
                doc.text(formatRupiah(item.total), margin + contentWidth, y + 4, { align: 'right' });

                y += 8;
            });

            // ============================================
            // ADD FOOTERS TO ALL PAGES
            // ============================================
            const totalPages = doc.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                addFooter(i, totalPages);
            }

            // Save PDF - try native jsPDF save first, fallback to blob
            const filename = `RM-Statement-${selectedMonth}.pdf`;

            try {
                // jsPDF's native save - works in most browsers
                doc.save(filename);
            } catch {
                // Fallback: Create blob with proper type and use FileSaver-like approach
                const pdfBlob = new Blob([doc.output('arraybuffer')], { type: 'application/pdf' });
                const url = window.URL.createObjectURL(pdfBlob);
                const link = document.createElement('a');
                link.style.display = 'none';
                link.href = url;
                link.setAttribute('download', filename);
                document.body.appendChild(link);
                link.click();

                // Cleanup
                setTimeout(() => {
                    document.body.removeChild(link);
                    window.URL.revokeObjectURL(url);
                }, 100);
            }

        } catch (error: any) {
            console.error('Failed to generate PDF:', error);
            alert(`Failed to generate PDF: ${error?.message || 'Unknown error'}`);
        } finally {
            setLoading(false);
        }
    };

    return (
        <button
            onClick={generatePDF}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-red-500 to-red-600 text-white rounded-lg font-medium shadow-md hover:shadow-lg transform hover:-translate-y-0.5 transition disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
        >
            {loading ? (
                <>
                    <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    <span>Generating...</span>
                </>
            ) : (
                <>
                    <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    <span>Export PDF</span>
                </>
            )}
        </button>
    );
}
